# 使用官方Python运行时作为父镜像
FROM python:3.8-slim

# 设置工作目录为/app
WORKDIR /app

# 将当前目录内容复制到位于/app中的容器中
COPY . /app

# 安装requirements.txt中指定的任何所需包
# 假设你的Flask应用的依赖在此文件中指定
RUN pip install --no-cache-dir -r requirements.txt

# 使端口5000可用于此容器外的服务
EXPOSE 5000

# 在容器启动时运行app.py
CMD ["python", "gh_interacter.py"]


